Generate AST from code
cqfn/diKTat pull request #188
Opened 2020-08-18 15:13 UTC by kentr0w

### What's done:
   Build code from text and generate a sub tree.
   closes #167

2020-08-18 15:19 UTC, petertrr commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/StringToNode.kt
> +     * Set property
Please provide more details/links regarding which error it helps to workaround and so on.

2020-08-18 15:20 UTC, petertrr commented on diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/utils/StringUtilsTest.kt
> +        println(node.prettyPrint())
Please remove

2020-08-18 15:21 UTC, petertrr commented on diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/utils/StringUtilsTest.kt
> +    fun `test inline function`() {
This is not an inline function in your example

2020-08-18 15:23 UTC, petertrr commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/StringToNode.kt
> +        return node.findChildByType(BLOCK)?.firstChildNode
How can it be nullable? Also, I think if supplied code is not valid (i.e. cannot be parsed) we should at least log error message, or even throw an exception.

2020-08-18 15:24 UTC, petertrr commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/StringToNode.kt
> +class StringToNode {
I suggest to rename this class to something like `ParsingUtils` or `KotlinParser` or something.

2020-08-18 15:25 UTC, petertrr commented on diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/utils/StringUtilsTest.kt
> +class StringUtilsTest {
Please provide some examples with parsing of multiline code fragments, invalid code fragments.

2020-08-24 14:39 UTC, petertrr requested changes
Another important task for this parser is ability to insert generated nodes into AST provided by framework. Actually, this is the main goal we had starting this.

2020-08-24 14:39 UTC, petertrr commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/KotlinParser.kt
> +        if (node.getChildren(null).size == ONE_CHILD)
Why this strange constant? It is allowed to use `1`, it is not considered as a magic number.

2020-08-24 14:39 UTC, petertrr commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/KotlinParser.kt
> +    fun createNode(text: String, isPackage: Boolean = false): ASTNode {
Please add documentation to this class, including some not obvious things we discussed, e.g. `createFile` is called only for `isPackage`.

2020-08-25 12:44 UTC, akuleshov7 commented on diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/utils/KotlinParserTest.kt
> +    @Test
please add separate tests for package names, separate test for imports

2020-08-25 12:51 UTC, akuleshov7 approved these changes

2020-08-25 14:49 UTC, petertrr commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/KotlinParser.kt
> +        else {
```suggestion
        node = if (isPackage) {
            ktPsiFactory.createFile(text).node
        } else {
```
Please add braces, it's really hard to read complex expressions without them.

2020-08-25 14:50 UTC, petertrr commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/KotlinParser.kt
> +        node = if (isPackage)
```suggestion
        val node = if (isPackage)
```
Why can't you do like this?

2020-08-25 14:52 UTC, petertrr commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/KotlinParser.kt
> +                } else {
Will this work for several imports? There should be node with type `IMPORT_LIST` in this case.

2020-08-26 13:05 UTC, petertrr reviewed
Could you try how your method works with KDocs? It would be useful for #74, for example. String with KDoc should be parsed as `KDOC` node with all it's complex structure: `KDOC_TEXT`, `LEADING_ASTERISK` etc.

2020-08-26 17:02 UTC, petertrr approved these changes
LGTM, let's merge it and try to use.

2020-08-26 17:02 UTC, petertrr commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/KotlinParser.kt
> +            text.lines().any { it.trim().indexOf("/**") == 0 }
```suggestion
            text.lines().any { it.trim().startsWith("/**") }
```

2020-08-27 09:55 UTC, merged

2020-08-28 16:20 UTC, akuleshov7 commented
> Another important task for this parser is ability to insert generated nodes into AST provided by framework. Actually, this is the main goal we had starting this.

@kentr0w did you fix this? create an issue if not