KDocMethods arguments present
cqfn/diKTat pull request #237
Opened 2020-09-04 20:10 UTC by kentr0w

## Actions checklist
* [x] Implemented Rule, added Warnings
* [x] Added tests on checks
* [x] Updated rules-config.json
* [x] Updated available-rules.md
* [x] closes #60

2020-09-06 12:47 UTC, petertrr requested changes

2020-09-06 12:47 UTC, petertrr commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/kdoc/KdocMethods.kt
> +                checkKDocParam(node)
It's better to do this check inside `checkSignatureDescription`, where comparison of declared and documented parameters is already being made. You can split it into smaller methods if you think it is becoming unreadable.

2020-09-06 12:47 UTC, petertrr commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/kdoc/KdocMethods.kt
> +                .filter { it.text == "@${PARAM_KEYWORD}" }
Take a look on how it's done in `getMissingParameters` method. Tags can be easily converted to psi objects to avoid comparison of strings.

2020-09-06 12:47 UTC, petertrr commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/kdoc/KdocMethods.kt
> +        kDocParamList.filter { functionParamList.map { funParam -> funParam.text }.indexOf(it.text) == NOT_FIND }.forEach {
```suggestion
        kDocParamList.filter { it.text !in functionParamList.map { funParam -> funParam.text }}.forEach {
```

2020-09-06 12:47 UTC, petertrr commented on diktat-rules/src/main/kotlin/generated/WarningNames.kt
> +    const val WRONG_KDOC_PARAM: String = "WRONG_KDOC_PARAM"
I think it's not worth creating a separate warning, please add this case to `KDOC_WITHOUT_PARAM_TAG` just with different `freeText` in error message.

2020-09-06 12:47 UTC, petertrr commented on diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/KdocParamPresentWarnTest.kt
> +                    |* @param В - russian letter
That was not obvious... :)

2020-09-06 13:04 UTC, akuleshov7 commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
> +    WRONG_DECLARATIONS_ORDER(true, "declarations of constants and enum members should be sorted alphabetically")
why comma removed?

2020-09-06 13:05 UTC, akuleshov7 commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/kdoc/KdocMethods.kt
> +        if (node.elementType == FUN) {
I would also not split such simple small code statements and use && here if possible

2020-09-08 11:50 UTC, petertrr commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/kdoc/KdocMethods.kt
> +        if (kDocTags != null && kDocTags.isNotEmpty()) checkKDocParam(node, kDocTags)
I'd rather not create a new function for this check, but merge it with `getMissingParameters` call and `handleParamCheck`.

2020-09-08 14:06 UTC, petertrr requested changes

2020-09-08 14:06 UTC, petertrr commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/kdoc/KdocMethods.kt
> +        val (missingParameters, kDocParamList) = getMissingParameters(node, kDocTags)
Name `kDocParamList` implies that it contains all params from kdoc, which it doesn't.

2020-09-08 14:06 UTC, petertrr commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/kdoc/KdocMethods.kt
> +        val paramCheckFailed = (missingParameters.isNotEmpty() || kDocParamList.isNotEmpty()) && !node.isSingleLineGetterOrSetter()
The original logic was as follows: if there are undocumented parameters but a method is a simple setter, than there is no need to add KDoc for it's parameter. But if there already is a KDoc which has wtong parameter, you should fix it regardless of whether method is simple setter or not.

2020-09-09 11:27 UTC, petertrr requested changes

2020-09-09 11:27 UTC, petertrr commented on diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/KdocParamPresentWarnTest.kt
> +                LintError(1, 1, ruleId, "${KDOC_WITHOUT_PARAM_TAG.warnText()} foo ()", true),
This warning is incorrect, it shouldn't be emitted in this case.

2020-09-09 16:05 UTC, petertrr approved these changes

2020-09-09 16:40 UTC, merged