Add all rule's in DiktatRuleSetProvider
cqfn/diKTat pull request #248
Opened 2020-09-07 13:22 UTC by kentr0w

### What's done:
    Added all rules
    closes #247

2020-09-07 13:28 UTC, petertrr commented
The idea was to also add some sort of test to avoid such issues in the future

2020-09-07 15:58 UTC, petertrr requested changes
The idea was to also add some sort of test to avoid such issues in the future

2020-09-08 11:42 UTC, aktsay6 requested changes

2020-09-08 11:42 UTC, aktsay6 commented on diktat-rules/src/test/kotlin/org/cqfn/diktat/util/DiktatRuleSetProvider4Test.kt
> +        val q = DiktatRuleSetProvider().get()
Please, rename variable

2020-09-08 14:01 UTC, petertrr requested changes
I'm not exactly positive about retrieving class names from file names and hard-coding directory structure, but as a quick and working as required solution which will affect only our own tests, I think this is fine. I have just a couple of minor style suggestions.

2020-09-08 14:15 UTC, kentr0w commented on diktat-rules/src/test/kotlin/org/cqfn/diktat/util/DiktatRuleSetProvider4Test.kt
> +                .map { it.substring(0, it.indexOf('@')) }
Yes, and it doesn't work

2020-09-08 14:49 UTC, petertrr commented on diktat-rules/src/test/kotlin/org/cqfn/diktat/util/DiktatRuleSetProvider4Test.kt
> +        val rulesName = DiktatRuleSetProvider().get().map { it::class.simpleName!! }.toMutableList()
```suggestion
        val rulesName = DiktatRuleSetProvider().get().map { it::class.simpleName!! }
```

2020-09-08 15:03 UTC, petertrr approved these changes

2020-09-08 15:22 UTC, aktsay6 approved these changes
LGTM

2020-09-08 15:22 UTC, merged