WildCards Import add documentation
cqfn/diKTat pull request #281
Opened 2020-09-14 11:54 UTC by kentr0w

### What's done:
    Added info

2020-09-14 13:18 UTC, akuleshov7 commented on diktat-rules/src/main/resources/diktat-analysis.yml
>  - name: FILE_WILDCARD_IMPORTS
let's start writing documentation here as comments to yml file

2020-09-14 13:19 UTC, akuleshov7 commented on diktat-rules/src/main/resources/diktat-analysis.yml
>  - name: FILE_WILDCARD_IMPORTS
@petertrr @kentr0w @aktsay6

2020-09-14 17:50 UTC, akuleshov7 requested changes
Denis, be quick! Fix it and merge

2020-09-15 12:46 UTC, petertrr approved these changes

2020-09-15 13:41 UTC, aktsay6 approved these changes
lgtm

2020-09-22 14:56 UTC, merged