Rule 3.14.2 string template format
cqfn/diKTat pull request #305
Opened 2020-09-18 10:36 UTC by aktsay6

### What's done:
 * Added rule logic
 * Added warn and fix test

## Actions checklist
* [X] Implemented Rule, added Warnings
* [X] Added tests on checks
* [X] Added tests on fixers
* [X] Updated diktat-analysis.yml
* [X] Updated available-rules.md

Closes #301

2020-09-21 12:11 UTC, akuleshov7 commented on diktat-analysis.yml
> +- name: REDUNDANT_CURLY_BRACES
add description
change names: STRING_TEMPLATE_CURLY_BRACES
STRING_TEMPLATE_QUOTES

2020-09-22 15:30 UTC, petertrr commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/StringTemplateFormatRule.kt
> +        if (node.elementType == SHORT_STRING_TEMPLATE_ENTRY) {
Please add comment about why these two `if`s cannot be combined in `if-else`

2020-09-23 10:38 UTC, petertrr commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/StringTemplateFormatRule.kt
> + * there should not be curly braces.
Please take a look at [this comment](https://github.com/cqfn/diKTat/issues/301#issuecomment-697280825). Please add it as fixme, I think we can't do anything with this now.

2020-09-23 10:45 UTC, petertrr requested changes

2020-09-23 10:45 UTC, petertrr commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/StringTemplateFormatRule.kt
> +                val identifierName = node.findChildByType(REFERENCE_EXPRESSION)!!.text
Will this branch trigger for strings like `"${1.0}"`? There can be expressions that don't have references.

2020-09-23 10:45 UTC, petertrr commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/StringTemplateFormatRule.kt
> +        val identifierName = node.findChildByType(REFERENCE_EXPRESSION)!!.text
Here I can't think of an example where there is no reference, but to be safe please add handling of null.

2020-09-24 15:59 UTC, petertrr approved these changes
LGTM

2020-09-24 16:06 UTC, merged