Rule 5.1.3 avoid nested functions
cqfn/diKTat pull request #361
Opened 2020-10-05 20:39 UTC by aktsay6

This pull request closes #356 

## Actions checklist
* [X] Implemented Rule, added Warnings
* [X] Added tests on checks
* [X] Added tests on fixers
* [X] Updated diktat-analysis.yml
* [X] Updated available-rules.md

## Fixme
 Need to detect all properties, which local function is using and add them to params of this function

2020-10-06 07:39 UTC, petertrr requested changes

2020-10-06 07:39 UTC, petertrr commented on diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter5/AvoidNestedFunctionsFixTest.kt
> +class AvoidNestedFunctionsFixTest : FixTestBase("test/paragraph5/nested_functions", ::AvoidNestedFunctionsRule) {
Please add an example that your rule doesn't break functions with dependent variables.

2020-10-06 07:39 UTC, petertrr commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/AvoidNestedFunctionsRule.kt
> +                    if (it != firstFunc) {
You can just `dropLast` on sequence instead of comparison.

2020-10-06 07:42 UTC, petertrr commented
Also your rule currently triggers on overridden member functions in anonymous objects declared inside other functions (e.g. `TestUtils.kt`, line 66).

2020-10-06 10:10 UTC, petertrr requested changes

2020-10-06 10:10 UTC, petertrr commented on diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter5/AvoidNestedFunctionsWarnTest.kt
> +class AvoidNestedFunctionsWarnTest : LintTestBase(::AvoidNestedFunctionsRule) {
Please add examples with anonymous objects

2020-10-07 10:48 UTC, kentr0w requested changes

2020-10-07 10:48 UTC, kentr0w commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/AvoidNestedFunctionsRule.kt
> +            paramsNames.add(it.name ?: "_")
Can you provide example where it will be null?

2020-10-07 10:48 UTC, kentr0w commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/AvoidNestedFunctionsRule.kt
> +        localProperties.forEach {
I think you can use `addAll()`. It will look prettier

2020-10-07 10:48 UTC, kentr0w commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/AvoidNestedFunctionsRule.kt
> +        func.getAllLeafsWithSpecificType(PROPERTY, localProperties)
Can you provide example where properties will be leaf?

2020-10-08 09:57 UTC, petertrr approved these changes
LGTM with some suggestions

2020-10-08 09:57 UTC, petertrr commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt
> +@Suppress("ForbiddenComment", "MagicNumber")
Why? We already have similar suppresses for detekt's inspection here, and need one for ours too

2020-10-08 09:57 UTC, petertrr commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/AvoidNestedFunctionsRule.kt
> +            parents().asSequence().toList().takeWhile { it.elementType != stopNode }.any { it.elementType == FUN }
```suggestion
            parents().asSequence().takeWhile { it.elementType != stopNode }.any { it.elementType == FUN }
```
Why do you need `toList` here?

2020-10-08 09:57 UTC, petertrr commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/AvoidNestedFunctionsRule.kt
> +        return paramsNames
```suggestion
        return (node.psi as KtFunction).valueParameters.map { it.name!! }
```

2020-10-08 10:40 UTC, kentr0w approved these changes
lgtm

2020-10-08 10:52 UTC, merged