Null safety in NewlinesRule
cqfn/diKTat pull request #634
Opened 2020-12-10 15:01 UTC by kentr0w

## Which rule and warnings did you add?
   Fixed bug
   closes #554

2020-12-11 06:51 UTC, petertrr requested changes

2020-12-11 06:51 UTC, petertrr commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt
> +    @Suppress("AVOID_NESTED_FUNCTION")
Where is a nested function here?

2020-12-11 06:51 UTC, petertrr commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt
> +        if (node.firstChildNode != null && node.firstChildNode?.elementType == ELVIS) {
```suggestion
        if (node.firstChildNode?.elementType == ELVIS) {
```
This check is redundant

2020-12-11 06:51 UTC, petertrr commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt
>          // at the beginning of the line.
This comment should be moved inside the second branch

2020-12-11 06:51 UTC, petertrr commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt
>       * @return true - if there is error, false, if there is no error and null if there is two calls in chain
```suggestion
     * @return true - if there is error, false, if there is no error
```
It doesn't return `null` anymore, does it?

2020-12-11 06:51 UTC, petertrr commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt
> +                ?.getCallChain()
These four lines can be extracted to a function and reused for left and right,

2020-12-11 06:51 UTC, petertrr commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt
> +        private val lineBreakAfterOperators = TokenSet.create(ANDAND, OROR, PLUS, PLUSEQ, MINUS, MINUSEQ, MUL, MULTEQ, DIV, DIVEQ, ELVIS)
Whyy? There shouldn't be a line break *after* `?:`, but it still appears in `lineBreakAfterOperators`. Why is this needed?

2020-12-11 06:51 UTC, petertrr commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt
> +        if (node.firstChildNode != null && node.firstChildNode?.elementType == ELVIS) {
Also, why are you checking it inside `handleOperatorWithLineBreakAfter`? There already is a little bit of special logic for `?:` in `handleOperatorWithLineBreakBefore`, this new logic should be placed there too.

2020-12-11 22:39 UTC, kentr0w commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt
> +    @Suppress("AVOID_NESTED_FUNCTION")
Forgot to end comment)

2020-12-14 09:24 UTC, petertrr approved these changes

2020-12-14 09:41 UTC, merged