AsyncAndSyncRule
cqfn/diKTat pull request #707
Opened 2021-01-14 14:28 UTC by kentr0w

### What's done:
   Implemented rule, added tests and documentation

## Actions checklist
* [x] Implemented Rule, added Warnings
* [x] Added tests on checks
* [x] Updated diktat-analysis.yml
* [x] Updated available-rules.md
* [x] closes #691

2021-01-15 09:49 UTC, petertrr requested changes

2021-01-15 09:49 UTC, petertrr commented on info/guide/guide-chapter-5.md
> +**Example**:
```suggestion
**Invalid example**:
```

2021-01-15 09:49 UTC, petertrr commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/AsyncAndSyncRule.kt
> +    private fun ASTNode.isRunBlocking() = this.elementType == REFERENCE_EXPRESSION && this.text == "runBlocking"
Maybe check that this reference expression actually belongs to lambda expression? Just in case it's used as reference or in import statement.

2021-01-15 09:49 UTC, petertrr commented on diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter5/AsyncAndSyncRuleTest.kt
> +    fun `test wrong case`() {
Please add positive example - that `async` and `launch` are allowed to be called from inside `runBlocking`

2021-01-18 08:27 UTC, merged

2021-01-18 11:13 UTC, akuleshov7 commented
@petertrr @kentr0w add it to the code style