Fix NPE in NewLineRule
cqfn/diKTat pull request #792
Opened 2021-03-05 14:46 UTC by Cheshiriks

### What's done:
* Fixed NPE in NewLineRule for lambda list argument

2021-03-08 18:32 UTC, akuleshov7 requested changes
please add tests and fix null issues :)

2021-03-08 18:32 UTC, akuleshov7 commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt
> +                if (list.first().treePrev != null) {
@Cheshiriks no tests, no merge of PRs? :)

2021-03-08 18:32 UTC, akuleshov7 commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt
> +                if (list.first().treePrev != null) {
why not avoid null check? Please see https://github.com/cqfn/diKTat/blob/master/info/guide/diktat-coding-convention.md#-433-null-safety

2021-03-09 08:26 UTC, petertrr requested changes

2021-03-09 08:26 UTC, petertrr commented on diktat-rules/src/test/resources/test/paragraph3/newlines/ListArgumentLambdaTest.kt
> +        foldIndexed("#") { index: Int, acc: String, pathPart: String ->
I believe this case should be an exception: we should either allow multiple args on the same line, or move the first too. Let's discuss. Also, please add a test with 3 args and no explicit types.

2021-03-09 09:42 UTC, petertrr approved these changes
lgtm, just fix code style

2021-03-09 11:33 UTC, merged