Bugfix. NPE in fixing of LineLength Rule
cqfn/diKTat pull request #858
Opened 2021-04-28 12:36 UTC by aktsay6

## What's done:
  * Fixed the bug

This pull request closes #842

2021-04-28 13:03 UTC, petertrr requested changes

2021-04-28 13:03 UTC, petertrr commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/LineLength.kt
> +    private fun fixFunction(wrongFunction: ASTNode, configuration: LineLengthConfiguration) {
Why did you support only annotated functions?

2021-04-28 13:03 UTC, petertrr commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/LineLength.kt
> +            is LongLineFixableCases.Fun -> fixFunction(fixableType.node, configuration)
Can we reuse existing logic for fixing long strings here?

2021-04-29 16:03 UTC, aktsay6 commented on diktat-rules/src/test/resources/test/paragraph3/long_line/LongLineRValueExpected.kt
> +" part" + "second Part"
Because string max length in test is 50

2021-04-30 08:37 UTC, aktsay6 commented on diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/LineLength.kt
> +     *         BinaryExpression - if there is two concatenated strings and new line should be inserted before `+`
Fixed

2021-04-30 14:49 UTC, merged